services:
  web:
    build: .
    container_name: noodlelibrary_app
    command: uvicorn noodlelibrary.main:app --host 0.0.0.0 --port 8000
    ports:
      - "127.0.0.1:8001:8000" 
    depends_on:
      - db
    env_file:
     - .env

  db:
    image: postgres:18
    container_name: noodlesdb
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backup:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
