services:
  db:
    image: postgres:18
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backup:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
